metadata:
#  title: БИБЛИОТЕКА LLVM2PY ДЛЯ АНАЛИЗА ПРОМЕЖУТОЧНОГО ПРЕДСТАВЛЕНИЯ LLVM И ЕЁ ПРИМЕНЕНИЕ В ОЦЕНКЕ СТЕПЕНИ РАСПАРАЛЛЕЛИВАНИЯ ЛИНЕЙНЫХ УЧАСТКОВ КОДА
#  subtitle: Учебное пособие
  author: "Павлов К.С., Советов П.Н."
  date: Москва – 2024
  figureTitle: Рисунок 
  figPrefix: рисунок
  titleDelim: .
  tableTitle: Таблица
  tblPrefix: табл. 
  numberSections: true
  sectionsDepth: 3
  secHeaderDelim: ". "
  toc-title: Оглавление
  bibliography: bibliography (3).bib
  link-citations: true
  csl: gost-r-7-0-5-2008-numeric-iaa.csl



